spring:
  profiles:
    active: local
    group:
      local: console-logging
      prod: console-logging, real-db, real-mail, real-logging, real-setting, file-error-logging, file-info-logging, slack-error-logging
---
mail:
  user1: test1
  pw1: test1
  user2: test2
  pw2: test2
  user3: test3
  pw3: test3
  user4: test4
  pw4: test4
  user5: test5
  pw5: test5
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
logging:
  slack:
    webhook-uri: test
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
setting:
  upload:
    password: test
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
