spring:
  profiles:
    active: local
    group:
      local: console-logging
      prod: console-logging, real-db, real-mail, real-logging, real-setting, file-error-logging, file-info-logging, slack-error-logging
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
logging:
  slack:
    webhook-uri: test
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
setting:
  upload:
    password: test
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
